name: Python Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies with Poetry
        run: |
          poetry config virtualenvs.create false
          poetry lock --no-update
          poetry install --with test
      - name: Test with pytest and check coverage
        run: |
          coverage run -m pytest
          coverage=$(coverage report -m | tail -1 | tail -c 4 | head -c 2)
          if (( $coverage < 90 )); then echo "Coverage failed at ${coverage}%"; exit 1; else echo "Coverage passed, ${coverage}%"; fi
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
